spring.application.name: @project.artifactId@
info.server.name: @project.artifactId@
info.server.version: @project.version@
info.build.name: @pom.build.finalName@
info.build.version: v1.0


# 日志级别 (名称以logging.level开头，后面跟要输入日志的包名， 这里定义的级别优先于logback.xml里定义的级别)
logging:
  level:
    root: info

server:
  port: 8888
  
spring:
  application:
    name: machine-service-provider
  datasource: 
    url: jdbc:mysql://smarthome.zniot.com:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: zniot888
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 10 
      maxActive: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 
#service discovery url
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:7070/eureka/
       
    
#mybatis
mybatis-plus:
  mapper-locations: classpath:config/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hl.common.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true